name: Validando push

on:
  push:
    Branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with: 
        node-version: 18.x
    - name: Instalando dependências
      run: npm i

    - name: Rodando os testes unitários
      run: npm run test
      env:
        CI: true