name: Validando pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Instalando NodeJs
      uses: actions/setup-node@v1
      with: 
        node-version: 18.x

    - name: Instalando dependências do projeto
    - run: npm i

    - name: Iniciando validação de testes unitários
    - run: npm run test
      env:
        CI: true
